on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run Pester
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Pester Action
      id: PSScriptAnalyzer
      uses: ./PesterActionV1
      with:
        script: 'tests/sample'
